# build-sic.yml — v1.0.0
# Purpose: Build & publish latest-sic-by-symbol.csv (daily).
# - Mirrors fetchListingsFast filters (Nasdaq/NYSE/NYSE American; exclude ETFs, test issues,
#   rights/warrants/units; plus extra fund-like screens).
# - Polite SEC usage (~8 req/sec to submissions).
# - Publishes to GitHub Pages alongside your shares artifacts.
#
# Schedules:
#   - Daily SIC build (UTC)
#   - (Optional) You already have a heartbeat in build-shares.yml to keep schedules alive.

name: Build SEC SIC

on:
  workflow_dispatch:
  schedule:
    - cron: "37 7 * * *"   # daily ~07:37 UTC (offset from shares job to avoid overlap)

env:
  UA: "Mozilla/5.0 MicroCap microcap@gmail.com"   # <-- keep descriptive UA (email/domain)

jobs:
  build-sic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create output dir
        run: |
          set -e
          mkdir -p public

      - name: Download nasdaq lists (UA) + SEC tickers JSON
        run: |
          set -e
          echo "[INFO] Downloading nasdaqlisted/otherlisted & tickers.json with UA..."
          curl -L --fail --retry 5 --retry-all-errors --retry-delay 2 \
               -H "User-Agent: $UA" \
               -H "Accept-Encoding: identity" \
               -o nasdaqlisted.txt \
               https://www.nasdaqtrader.com/dynamic/symdir/nasdaqlisted.txt

          curl -L --fail --retry 5 --retry-all-errors --retry-delay 2 \
               -H "User-Agent: $UA" \
               -H "Accept-Encoding: identity" \
               -o otherlisted.txt \
               https://www.nasdaqtrader.com/dynamic/symdir/otherlisted.txt

          curl -L --fail --retry 5 --retry-all-errors --retry-delay 2 \
               -H "User-Agent: $UA" \
               -H "Accept-Encoding: identity" \
               -o company_tickers.json \
               https://www.sec.gov/files/company_tickers.json

          echo "[DEBUG] Sizes:"
          wc -c nasdaqlisted.txt otherlisted.txt company_tickers.json || true
          echo "[DEBUG] Peek nasdaqlisted header:"
          head -n2 nasdaqlisted.txt || true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Build SIC CSV
        run: |
          set -e
          python3 build_sic.py nasdaqlisted.txt otherlisted.txt company_tickers.json public
          echo "[INFO] Outputs:"
          ls -lh public
          echo "[INFO] Head of latest-sic-by-symbol.csv:"
          head -n 10 public/latest-sic-by-symbol.csv || true
          echo "[INFO] meta-sic.json:"
          cat public/meta-sic.json || true

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public
